server:
  port: 8770
#服务名称
spring:
  cloud:
    bus:
      enabled: true  #消息总线配置
      trace:
        enabled: true  #消息总线配置
  rabbitmq:    #rabbitmq配置
    host: localhost
    port: 5672
    username: guest
    password: guest

#暴露bus-refresh的监控信息
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
    
env: test
branch: master
